# Site information
site_name: twomes-generic-esp-firmware library documentation
site_description: Documentation for the Twomes generic firmware library.
site_url: https://energietransitie.github.io/twomes-generic-esp-firmware

# Repository
repo_url: https://github.com/energietransitie/twomes-generic-esp-firmware
edit_uri: edit/main/docs/

# Copyright
copyright: License <a href="http://creativecommons.org/licenses/by/4.0">CC BY 4.0</a>, <a href="https://www.windesheim.nl/energietransitie">Research group Energy Transition, Windesheim University of Applied Sciences</a> 

# Theme
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    edit: material/file-edit-outline
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

# Navigation pages
nav:
  - Home: index.md
  - Getting started:
    - Prerequisites: starting/prerequisites.md
    - Using a devcontainer: starting/devcontainer.md
    - Use as library in a new project: starting/new-project.md
    - Use as library in an existing project: starting/existing-project.md
  - Reference:
    - Measurements and uploading: reference/measurements-and-uploading.md
    - Scheduler: reference/scheduler.md
    - Measurement tasks: reference/tasks.md
  - Documenting:
    - Device installation manual: documenting/installation-manual.md
    - Device info page: documenting/device-info.md
  - Releasing:
    - Building: releasing/building.md
    - Releasing: releasing/releasing.md
    - Secure bootloader: releasing/secure-boot-bootloader.md
    - Secure firmware: releasing/secure-boot-firmware.md
  - Deploying:
    - Prerequisites: deploying/prerequisites.md
    - Device preparation: deploying/device-preparation.md
    - Configure presence detection: deploying/configure-presence-detection.md
  - Provisioning:
    - Testing: provisioning/testing.md

