# Site information
site_name: twomes-generic-esp-firmware library documentation
site_description: Documentation for the Twomes generic firmware library.
site_url: https://energietransitie.github.io/twomes-generic-esp-firmware

# Repository
repo_url: https://github.com/energietransitie/twomes-generic-esp-firmware
edit_uri: edit/main/docs/

# Copyright
copyright: License <a href="http://creativecommons.org/licenses/by/4.0">CC BY 4.0</a>, <a href="https://www.windesheim.nl/energietransitie">Research group Energy Transition, Windesheim University of Applied Sciences</a> 

# Theme
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    edit: material/file-edit-outline
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

# Navigation pages
nav:
  - Home: index.md
  - Starting:
    - Prerequisites: starting/prerequisites.md
    - Using a devcontainer: starting/devcontainer.md
    - Using the library in a new project: starting/new_project.md
    - Using the library in an existing project: starting/existing_project.md
  - Measuring:
    - Adding measurements : measuring/measuring.md
    - Scheduling: measuring/scheduling.md
    - Running measurement tasks: measuring/running_tasks.md
    - Uploading: measuring/uploading.md    
  - Documenting:
    - Device installation manual: documenting/installation_manual.md
    - Device info page: documenting/device_info.md
  - Releasing:
    - Building: releasing/building.md
    - Releasing: releasing/releasing.md
    - Securing the bootloader: releasing/secure_boot_bootloader.md
    - Securing firmware: releasing/secure_boot_firmware.md
  - Deploying:
    - Prerequisites: deploying/prerequisites.md
    - Preparing devices: deploying/device_preparation.md
    - Configuring presence detection: deploying/configuring_presence_detection.md
  - Provisioning:
    - Overview: provisioning/overview.md
    - Testing: provisioning/testing.md

