name: Build CI
# Trigger on any change that is not markdown and not in the main branch.
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List all of the PlatformIO platforms to build
        platformio_env:
          - ESP32DEV
          - M5STACK_COREINK

        # List of the examples to build.
        test_dir:
          - test/generic_test
   
    steps:
      # Checkout repository.
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Setup Python (needed by PlatformIO)
      - name: Setup Python
        uses: actions/setup-python@v2

      # Setup PlatformIO.
      - name: Setup PlatformIO
        run: pip install platformio
        
      # Change library from github to local directory in platformio.ini.
      - name: Use local library version
        env:
          TEST_DIR: ${{ matrix.test_dir }}
        run: sed -i 's=https://github.com/energietransitie/twomes-generic-esp-firmware=../../=g' $TEST_DIR/platformio.ini
      
      # Build the PlatformIO project.
      - name: Build PlatformIO project
        env:
          PLATFORMIO_ENV: ${{ matrix.platformio_env }}
          TEST_DIR: ${{ matrix.test_dir }}
        run: pio run -e $PLATFORMIO_ENV -d $TEST_DIR
